name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.0, etc.
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Get version info
      id: version
      shell: pwsh
      run: |
        if ("${{ github.ref }}".StartsWith("refs/tags/")) {
          $version = "${{ github.ref }}".Replace("refs/tags/", "")
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "is_release=true" >> $env:GITHUB_OUTPUT
        } else {
          $date = Get-Date -Format "yyyyMMdd"
          $sha = "${{ github.sha }}".Substring(0,7)
          $version = "$date-$sha"
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "is_release=false" >> $env:GITHUB_OUTPUT
        }
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Install your app dependencies if you have a requirements.txt
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        }
        
    - name: Build standalone executable with PyInstaller
      run: |
        pyinstaller reminder.py --onefile --noconsole --add-data "alarm;alarm" --add-data "alarm1;alarm1" --add-data "alarm24;alarm24" --add-data "img;img" --icon=img/icon.png --name CeLOE_Desktop-portable
        
    - name: Rename executable with version
      run: |
        Rename-Item -Path "dist/CeLOE_Desktop-portable.exe" -NewName "CeLOE_Desktop-portable-${{ steps.version.outputs.version }}.exe"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CeLOE_Desktop-portable-${{ steps.version.outputs.version }}
        path: dist/CeLOE_Desktop-portable-${{ steps.version.outputs.version }}.exe
        retention-days: 30
        
    - name: Create Release
      if: steps.version.outputs.is_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/CeLOE_Desktop-portable-${{ steps.version.outputs.version }}.exe
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Windows Standalone Executable - ${{ steps.version.outputs.version }}
          
          Download the .exe file and run it directly - no installation required!
          
          **Features:**
          - No Python installation needed
          - No terminal/command prompt window
          - Completely standalone executable
          - Just download and double-click to run
          
          **Note:** Windows may show a security warning for unsigned executables. Click "More info" then "Run anyway" if prompted.
          
          ### Built from commit:
          `${{ github.sha }}`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}